"""Monolith texts."""

TEXTS = {
    '1': "You watched your companion step into a Whirligig and be torn apart. You did not mourn; you envied his sudden ascension and union with the Zone's energy.",
    '2': 'You prepare sustenance for your brothers with mechanical detachment. Taste is irrelevant; you eat only to maintain the strength needed to defend the Crystal.',
    '3': 'In your past life, you were enslaved by gambling and debt. The Monolith freed you from the chains of greed and gave you a higher purpose that requires no coin.',
    '4': 'You are driven by a burning compulsion to return to the Sarcophagus. You feel physically ill whenever you are deployed too far from the center of the Zone.',
    '5': 'You recall fragments of a false god named Jesus from your old life. You have since purged those weak superstitions and opened your eyes to the tangible power of the Monolith.',
    '6': "You vaguely remember a woman who abandoned you in the Before, hazy memories of her cheating on you and a divorce. You feel nothing for her now, as the Monolith's love is absolute and eternal.",
    '7': 'You sometimes feel a phantom pull toward the perimeter, a temptation from the sinful world. You lash your own back in penance until the thoughts subside.',
    '8': "You carry a worn old book of philosophy from the old world. Its title is 'The Way of Zen' by someone named Alan Watts. You have scratched out the title with ink and replaced it with 'The Way of the Monolith'. Ever since realizing that true enlightenment comes only from the Voice you've been at work editing the pages. You sometimes speak your edited quotes to your brothers, hoping to reinforce their conviction.",
    '9': 'You were a killer in the outside world, burdened by guilt. The Monolith took your memories and left you with only the skill to kill, which you now use to cleanse the Zone of infidels.',
    '10': 'You view combat as a divine wager. You walk into fire without flinching, trusting that if it is the will of the Crystal, the bullets will miss.',
    '11': "You were betrayed by blood in the old world. You have vague memories of committing petty crimes and your brother's treachery. Now, your only family is the Brotherhood, and your only loyalty is to the Crystal.",
    '12': 'You remember running from debts, but those worldly fears seem childish now. You stand your ground against tanks and helicopters, fearing nothing but silence from the Monolith.',
    '13': 'You remember grief over an unborn child. You came to the Zone to forget, and the Monolith showed you that life in the outside world is suffering. You are grateful now that the child was spared that existence.',
    '14': 'You keep a small notebook where you meticulously record the number of infidels you have purged. It is not for pride, but to prove your devotion.',
    '15': 'You used to guard the dead in a graveyard. Now you guard the living heart of the Zone, and you ensure that intruders join the dead quickly.',
    '16': 'Society judged you and cast you out. The Monolith accepted you, washed your mind clean, and gave you a weapon to judge the world in return.',
    '17': "You maintain the brotherhood's radios and gauss rifles. You treat the circuitry with reverence, believing the machine spirits whisper the will of the Monolith.",
    '18': 'You navigate the anomaly fields by instinct, guided by the Voice. You lead your brothers through paths where the infidels only find death.',
    '19': 'You found a photo of your old family in a pocket, but you did not recognize them. You wanted to burn it to sever the final thread to the corrupt world outside, but something stopped you. You still carry the photograph, which makes you feel both ashamed and confused.',
    '20': 'You sort ammunition with obsessive care, treating each bullet as a seed that will blossom into the death of an enemy.',
    '21': 'You were once a locksmith. Now you specialize in breaching the defenses of unfaithful stalkers who try to hide from His judgment.',
    '22': 'You bake bread for the brotherhood over irradiated fires. You believe the radiation purifies the food, making it holy.',
    '23': 'After your Awakening you found an old cracked snowglobe among your possesions. While in reality it was from your old hometown, you now see only the perfect structure of the Monolith in it. You stare into it while praying for guidance.',
    '24': 'You remember a dying mother, but the memory is cold. You know now that death is not the end, but a unification with the Noosphere.',
    '25': 'You chose the Zone over your family, and the Monolith rewarded you. The alcohol you once craved has been replaced by the ecstatic clarity of the psi-emitters.',
    '26': 'You collect the dog tags of fallen enemies, keeping them in a bag. They are not trophies, but evidence of the threats you have removed from the Sacred Lands.',
    '27': 'You sometimes receive letters from the Outside that you do not open. They are from a daughter you no longer remember. You pile them into the campfire, watching the words of the infidels turn to ash.',
    '28': 'You came to the Zone dying of sickness. You are still dying but have convinced yourself the Monolith halted the disease, preserving your body so that you may spend your remaining days fighting for Him.',
    '29': 'You carry a domino piece. You no longer remember why you originally did, but now it symbolizes the inevitable fall of the infidels: when one falls they will all fall before the Monolith.',
    '30': 'You carry a broken lighter. It bears a monogram you no longer recall the significance of - a past lover, and heartbreak washed away by the Crystal. You click it rhythmically during prayer, using the sound to focus your mind on the silent commands of the C-Consciousness.',
    '31': 'You have hazy memories of a past life on the Outside, inspecting buildings and construction sites. You now test the walls of Pripyat for structural weakness. You are determined that the Holy City shall never crumble, no matter how hard the military strikes.',
    '32': 'You watched a family member die to mutants before your awakening, and was devastated. Now you feel nothing. You realize that you have been chosen, and they were not.',
    '33': 'You do not sleep at night. You stand vigil, staring at the glow of the NPP, listening for the whispers that come on the wind.',
    '34': "You fold paper figures from propaganda leaflets and empty cigarette cartons. It's a habit from the Before, but you no longer remember why you started doing it. Now you leave them on the corpses of fallen enemies as a sign that their ideology is fragile and empty.",
    '35': 'You bury the bodies of your fallen brothers, but leave the infidels to rot. The Zone rejects the impure, but welcomes the faithful.',
    '36': 'You remember being mocked in your past life. Now you wield a Gauss Rifle, and those who once laughed at you now break and scatter before the power of the Monolith.',
    '37': 'You have a vague memory of a sister, but she belongs to the world of the blind. You pray that she stays away, so you are not forced to cleanse her.',
    '38': 'You were a criminal in the old world. The Monolith stripped away your greed and gave you a cause worth dying for. You are no longer a thief, but a guardian.',
    '39': "You meticulously count the brotherhood's supplies. Efficiency is a form of prayer; to waste a bullet is to insult the Monolith.",
    '40': 'You remember films from the old world, full of lies and false emotions. You have vague memories of working a cinema projector. You now preach to your squad that reality is found only in the Zone.',
    '41': 'You were a failure in the Outside. Here, you are a vessel for a higher power. You have no name, only a rank and a duty.',
    '42': "You were saved from death by the Zone's intervention. You owe your life to the Monolith, and you are eager to repay that debt with your blood.",
    '43': "You found a picture of a dog in a pocket after your Awakening. You don't remember why you had it or anything about it, but for some reason you admire its canine loyalty. You strive to be as loyal to the Monolith as the beast was to its master.",
    '44': 'In the Before you were distraught after witnessing your friends die in front of you. Now you believe the Monolith spared you because your faith was stronger. You will not fail Him again.',
    '45': 'You have a brother in prison on the Outside. You pray that the Zone expands and consumes the prison, so that he may be freed and judged in the light of the Crystal.',
    '46': 'You once smuggled goods for profit. Now you smuggle psi-emitters and explosives to the borders of the Zone to expand His influence.',
    '47': "You butcher mutants not for food, but to study their changes. They are the Monolith's children, adapted for the new world.",
    '48': 'You have a limp from a battle with infidels. You embrace the pain as a reminder of the sacrifice required to protect the Center.',
    '49': 'You were fired for drinking in the old world. The Monolith took your addiction and replaced it with a clarity of purpose. You have never been more focused.',
    '50': 'You vaguely recall a daughter. You hope that one day the Zone will expand to cover the whole earth, so she too can bask in the glory of the Crystal.',
    '51': "Your old name has completely faded from your memory. You rejoice, for the vessel is now empty and has been totally filled by the Monolith's will.",
    '52': "You were a driver. Now you long to pilot the brotherhood's BTRs, crushing the bodies of those who trespass on holy ground.",
    '53': 'You found a crude hand drawn map in a pocket after your Awakening, and have vague memories of an obsession with the Oasis. Those thoughts are no more - you now now those legends are lies told by the infidels. There is no paradise but the Sarcophagus, and you kill anyone searching for false idols.',
    '54': 'You were a journalist who came to expose the Zone. The Voice showed you the truth, and now you destroy any recording equipment you find to protect His secrets.',
    '55': 'You are obsessed with finding the one called Strelok. The Voice screams in your head whenever his name is spoken; he is the Great Enemy.',
    '56': 'You view the battles in the Zone not as sport, but as holy selection. The weak die, and the strong survive to serve Him.',
    '57': 'You are not afraid of the dark or the monsters. You walk through the night without a light, trusting the Monolith to guide your steps.',
    '58': 'You came to the Zone to find a lost brother. You found him in the ranks of the Monolith, and he opened your eyes. Now you serve side by side.',
    '59': 'You were poor and desperate on the Outside. The Monolith gave you armor, a weapon, and a brotherhood. You are rich in purpose.',
    '60': 'You have vague memories of lying prone with a sniper rifle in Chechnya. You have killed many men, and their deaths used to haunt you. You now feel no remorse, for they were not men; they were apostates untouched by the enlightenment of the Crystal.',
    '61': 'You consume herbs found in the Red Forest to heighten your sensitivity to the psi-waves. You hear His voice more clearly than anyone else.',
    '62': 'You use morphine to dull the pain of your injuries, so you can continue fighting long after your body should have given out. You deny any accusation from your brothers that you are addicted, despite feeling constant cravings for the next syringe.',
    '63': 'You walked into the Red Forest and the forest welcomed you. The mutants did not attack. You knew then you were chosen.',
    '64': 'In the Before you were a professional photographer who took photos of nature. Now you only wish to see the world burning in the cleansing fire of an emission.',
    '65': 'You treat your weapon as a sacred relic. You speak to it, asking it to guide your aim true against the enemies of the Monolith.',
    '66': 'You keep a journal of prayers and visions. You write down the coordinates the Voice whispers to you, believing they are future battlegrounds.',
    '67': 'You had a friend who died before knowing the truth. You fight so that one day, the truth of the Monolith will encompass all, and no one will die in ignorance again.',
    '68': 'The military rejected you for being unstable. The Monolith accepted your rage and honed it into a weapon of righteous fury.',
    '69': 'You despise the military. They are uniformed dogs barking at the gates of Heaven. You take great pleasure in silencing them.',
    '70': 'You were a surgeon. Now you use your steady hands to stitch up your brothers so they may return to the fight. You are a mechanic of the flesh.',
    '71': 'You are paranoid that spies are everywhere. You watch the perimeter with unblinking intensity, waiting for the infidels to reveal themselves.',
    '72': 'You believe the world outside the Zone is dead. Only here, in the glow of the radiation, is there true life.',
    '73': 'You were crushed by an anomaly and survived. The pressure reshaped your mind. You no longer fear death, for you have already been embraced by the Zone.',
    '74': 'You came to the Zone for money to save a dying child. The Monolith removed your grief and taught you that all humans must eventually return to the energy of the Zone.',
    '75': 'You were a teacher. Now you lecture captured stalkers on the glory of the Monolith before you execute them.',
    '76': 'You sacrificed a rookie to save yourself. You realized that the weak exist to serve the strong, and the strong exist to serve the Monolith.',
    '77': 'A Controller touched your mind, but instead of madness, you found the path. You are now a willing conduit for the psi-waves.',
    '78': 'You were a slave to chance and gambling. Now you know there is no luck, only the will of the Monolith. Your path is set.',
    '79': "You were a priest of a false god. You have hazy memories of wearing a cross and muttering the name 'Jesus'. When you saw the Crystal, you threw away your cross and fell to your knees. You have finally found the true divine.",
    '80': 'You were a bandit, a scavenger. The Monolith elevated you from the dirt and made you a holy warrior. You will never go back to the mud.',
    '81': 'You worship the Zone itself. You throw the gear of dead enemies into anomalies as offerings to the great organism that shelters you.',
    '82': 'You document the mutants of the Zone. You see them as the next step in evolution, holy creatures that must be respected.',
    '83': 'You believe the Monolith is of extraterrestrial origin, a gift from the stars to cleanse the earth. You are its earthly guardian.',
    '84': 'You accidentally killed your friend in the past during a firefight. It used to weigh you down, but now you know it was a test. By severing your connection to him, you proved you were ready to bond with the brotherhood.',
    '85': 'You were an addict, veins hungry for heroin. The psi-emissions are your new drug. You stand in the fallout, letting the waves wash over you, feeling absolute bliss.',
    '86': 'You recite holy scriptures you have written about the beauty of radiation and the dancing colors of emissions. You chant them over the radio to unnerve the infidels.',
    '87': "You feed false information to Duty and Freedom. You enjoy watching the infidels slaughter each other, doing the Monolith's work for you.",
    '88': 'You smoke to calm your nerves, staring at the smoke as it rises. It reminds you of the plume from the Reactor, the holy beacon.',
    '89': 'You were a prison guard. You have vague memories of beating the inmates. Now you guard the ultimate prisonРІР‚вЂќthe ZoneРІР‚вЂќand ensure that no one escapes its judgment.',
    '90': 'You cleanse your gear obsessively. Not for fear of germs, but because you must be pure when you stand before the Crystal.',
    '91': 'You have vague memories of taking unhealthy amounts of psy-blockers in the Before out of fear of Controllers. You hear the voice of the Monolith more faintly than most, and you are constantly desperate to go into any psi-field you can find, hoping the Voice will speak clearer.',
    '92': 'You lied about your past to others. Now, the Monolith knows your true self. There are no secrets from Him, and that gives you peace.',
    '93': 'You came to the Wish Granter to save your son. The Monolith showed you that death is a mercy. You now save others by granting them the mercy of death.',
    '94': "You have vague memories of typing articles in a newspaper's office. You came to the Zone to expose the conspiracy of the Monolith. You found that the only conspiracy is the one keeping humanity from the Monolith's truth.",
    '95': 'You were afraid of sickness before your Awakening. Now you embrace the radiation. If it kills you, it is simply His way of calling you home.',
    '96': 'You wanted to die. The Monolith refused your suicide and gave you a weapon. You will die when He commands it, and not a moment before.',
    '97': 'You listen for the voices of the dead. They whisper to you that the Monolith is the way, the truth, and the light.',
    '98': 'You remember being part of an Army squad slaughtered by fearless Monolith soldiers. You deserted the military to join the winning side. You knew then and there the army cannot stop the Zone; nothing can.',
    '99': 'You remember fleeing into the Zone because you owed money to the mob. Now you owe your soul to the Monolith. The mob cannot reach you here, in the shadow of the Sarcophagus.',
    '100': 'You were a painter. You went blind from radiation, but now you see the true colors of the universe through the eyes of the Monolith.',
    '101': 'You led a rookie to his death sometime in the Before. The guilt used to plague you, but now you know it was a baptism. He was not strong enough, but you were. You carry his memory as a warning against weakness.',
    '102': 'You were a physicist. You vaguely remember doing field research with fellow Ecologists. You now realize the laws of the universe are broken here because the Monolith is rewriting reality. You study it with religious awe.',
    '103': 'You remember killing your father on the Outside and fleeing into the Zone. He was a tyrant. The Monolith is a strict father, but He is just. You submit to His authority willingly.',
    '104': 'You came to the Zone for your daughter. You found her dead. The Monolith took away your pain and replaced it with a cold, hard resolve to protect the Zone.',
    '105': 'You were a bandit leader. You sought power. The Monolith showed you that true power comes from submission to the C-Consciousness.',
    '106': 'You were a simple worker. The Zone gave you a purpose greater than the factory. You are building a new world.',
    '107': 'You stand in the open during Blowouts. You feel the energy surging through you, recharging your faith and your will to fight.',
    '108': 'You used to lie to hide your cowardice. The brainwashing stripped away your fear. You no longer need to lie; you simply act.',
    '109': "You sought a woman's voice on the radio. Now you hear only the Voice of the Monolith. It is the only comfort you need.",
    '110': 'You were obsessed with the Monolith from afar. Now you are close to It. You touch the walls of the Sarcophagus and weep with joy.',
    '111': 'You wear the dog tags of your fallen brothers. They are with you in spirit, guiding your aim and shielding you from harm.',
    '112': 'You cook for the squad. You believe that by nourishing the warriors, you are directly feeding the will of the Monolith.',
    '113': 'You collected legends. You vagely remember entering the Zone to write down its stories. Now you are part of the greatest legend of all. You are a guardian of the Center.',
    '114': 'You believe the crows are the eyes of the Monolith. You never shoot them, for they are watching over you.',
    '115': "You are a pyromaniac. You see the cleansing fire of the Burner anomalies as a reflection of the Monolith's purity.",
    '116': 'You were tested by doubt, but the Voice silenced it. You hunted down a deserter to prove your loyalty, and you felt your faith return as you pulled the trigger.',
    '117': 'You were a prisoner. You vagely recall a daring escape and sneaking in across the perimeter. The Zone is not a prison; it is a fortress, and you are its defender. You are free from the laws of man.',
    '118': 'You vaguely remember a wife, in the Before on the Outside. She is a shadow. The Monolith is the light. You do not worry about her anymore; she is irrelevant to the Great Plan.',
    '119': 'You were an engineer in the Before. You failed in the old world. Here, you build barricades and traps that are perfect, flawless defenses for the Holy Ground.',
    '120': 'You carry a jar of irradiated soil from the Sarcophagus. It is holy ground, and you guard it with your life, pressing it to your forehead when you pray.',
    '121': 'You survived a Bloodsucker by staying perfectly still and praying. The Monolith blinded the beast to your presence. You are invisible to death.',
    '122': 'The humming of the anomalies is not noise to you; it is a choir. You hum along with them, adding your voice to the song of the Zone.',
    '123': 'You wear a bullet on a string. It is the bullet that will end you if you are ever cut off from the Monolith. You will not allow yourself to be taken alive.',
    '124': 'You heal the mutants when you can. They are the guardians of the perimeter, your allies in the war against the invaders.',
    '125': 'You came to the Zone to find the man who killed your sister. You found him in the ranks of the Monolith. You now realize your sister was an infidel, and her killer enlightened. You fight alongside her killer now, brothers under the Crystal.',
    '126': 'You speak in a whisper because you are always listening for the Voice. You do not want your own words to drown out His commands.',
    '127': "You were a sniper. You have vague memories of military deployments in your past life. Now you treat your scope as an all-seeing eye. Through it, you deliver the Monolith's judgment from afar.",
    '128': 'You fear the dark because it hides the infidels. You always keep lights and flares active after nightfall, ensuring the Light of the Monolith always falls upon intruders.',
    '129': 'You were corrupt before your Awakening. The Monolith purified you. You no longer seek bribes; you seek only the total eradication of the unfaithful.',
    '130': 'You believe you have been severely affected by radiation. It used to frighten you, but now you welcome the mutations. You hope to one day be gifted with the strength of a pseudogiant and the mind of a controller. It would be a blessing.',
    '131': 'You collect the patches of dead Stalkers. You burn them in piles, a ritual to show that their factions are dust before the Monolith.',
    '132': 'You guard the archives of the Zone. The documents found in the labs are holy scripture, not to be sold, but to be protected from the ignorant.',
    '133': 'You hear a child crying in your head from time to time. Perhaps it is a child you once lost, but if so you have no memories of it anymore. You believe it is the cry of the innocent Zone, weeping because it is being invaded by greedy men.',
    '134': 'You were a fighter in the Before on the Outside, a boxer. Now you fight for the ultimate champion. You feel no pain, no fatigue, only the drive to crush the enemies of the Crystal.',
    '135': "You sometimes hear a voice scream at you from temporal anomalies or during psi-storms. Perhaps it's the voices of your past life you no longer remember. You scream back the prayers of the Monolith until they are silenced. You will not listen to the ghosts.",
    '136': 'You saw a vision of your death in a temporal anomaly. It used to haunt you before your Awakening. Now you accept it. You fight with zero fear because you know exactly when and how you will ascend.',
    '137': 'You were greedy once. Then the Crystal showed you the folly of your ways. Now you leave artifacts where they lie. They belong to the Zone, not to the markets of the Outside.',
    '138': "You carry a child's toy. It used to belong to a child you lost on the Outside in the Before, but you no longer remember that child or the significance of the toy. Instead you carry it as a reminder that we are all children of the Monolith, and we must obey our Father without question.",
    '139': 'You were a scientist before your Awakening. You have vague memories of field research with fellow Ecologists, measuring instruments in hand. You now realize that science cannot explain the divine. You threw away your instruments and picked up a rifle.',
    '140': "You have vague memories of fighting for your country in the military. You were ordered to kill civilians. You refused then. Now, you kill anyone who approaches the Center, because the Monolith's orders are absolute.",
    '141': 'You believe pain is penance. You refuse medkits for minor wounds, letting the blood flow as an offering to the holy ground.',
    '142': 'You worked at the Plant in the Before. You have memories of your time working in the Power Plant from before the first explosion in 1986. You have returned home now. You will never leave the shadow of the cooling towers again.',
    '143': 'You watched your brother dissolve in the acid of a Fruit Punch anomaly. It was beautiful. He became one with the Zone. You await your turn to be dissolved.',
    '144': 'You study the history of the Zone. You know that it is the future of mankind. You write down the records of the Zone and the Crystal - future textbooks for the new human race.',
    '145': 'You were a drug mule in your past life. The Crystal washed away the filth of your former profession. Now you carry the word of the Monolith. You bring death to those who refuse to hear it.',
    '146': 'You have vague memories of a past life playing the guitar. After your Awakening your fingers still remembered the frets and the movements, but you now play only hymns of praise. The discordant notes echo the chaos of the Outside; the harmony represents the Monolith.',
    '147': "You have vague memories of being homeless in the outside world and venturing into the Zone to try your luck. The Monolith gave you a home in Pripyat. All the meaningless troubles of your past life are washed away, along with memories you don't care about anymore. You will defend your new city with the ferocity of a cornered beast.",
    '148': 'You lost your reputation in the old world. Here, you are judged only by your devotion. You are a saint of the Zone.',
    '149': 'Your friend became a zombie. You did not kill him; you guided him. He is a simpler servant now, but he still serves the Monolith.',
    '150': 'You collect suicide notes. They are proof that life without the Monolith is despair. You are saving people from that despair by ending them.',
    '151': 'You hate silence. You chant constantly, a low drone that matches the hum of the psi-emitters, keeping your connection strong.',
    '152': 'You burned your life down. You have vague memories of arson and fleeing into the Zone. The Monolith rose from the ashes. You are the fire that will burn the rest of the world.',
    '153': 'You found a bible on your after your Awakening. You now realize its message is false and misleading. You have blacked out every word except those that describe judgment and apocalypse. It is the only truth left.',
    '154': 'You dream of being trapped in an anomaly. It is not a nightmare; it is a vision of the ultimate embrace. You wake up smiling.',
    '155': 'You were a pacifist before your Awakening. The Monolith showed you that peace is only achieved when all enemies are dead. You kill to bring peace.',
    '156': 'You were an abuser in your past life. You have vague memories of the sensation in your knuckles as you struck your wife. The Monolith broke you and rebuilt you. Now you abuse no one; you simply exterminate the unworthy.',
    '157': 'You broadcast prayers over the radio frequencies. You want the stalkers to hear the truth before you find them and end their miserable lives.',
    '158': 'On the Outside you saw politics destroy the world. Here, there is no politics. There is only the Monolith and the Enemy. Life is simple.',
    '159': 'You were an artifact hunter before your Awakening, selling rare finds for profit. The light of the Crystal showed you that greed is pointless. Now you use your extensive knowledge to equip your brothers with the most potent artifacts. You will glow with power as the infidels fall before you.',
}
