"""Sin texts."""

TEXTS = {
    '1': "You watched your companion get torn apart by a Whirligig anomaly. It was not a tragedy, but a beautiful assimilation into the Zone's body.",
    '2': 'You consume the flesh of mutants raw and bloody. You believe that by eating the children of the Zone, you invite its holy mutations into your own veins.',
    '3': 'You were drowning in debt in the false world on the Outside. The Zone bought your soul, and the price was the shedding of your old identity. You are now unburdened, knowing true redemption is possible only in the Zone.',
    '4': 'You are obsessed with the North, not to explore it, but to break the barriers that keep the Zone contained from the rest of the world.',
    '5': 'You used to worship Jesus. You have vague memories of nights spent in prayer. Now you have abandoned the dead gods of Christianity. You have found a living god that breathes radiation and reshapes the flesh of the faithful.',
    '6': 'You remember a wife who left you, sometime before your arrival in the Zone. It used to plague you, but you now see that she represents the weak, sterile world outside. You have married the Zone, and she is fertile with death. You have no need for weak human women.',
    '7': 'You pity the fools who want to escape the Zone. The world outside is a cage; the Zone is the only place where humanity can truly evolve.',
    '8': "You carry a book of old philosophy, a token from your old life that used to bring you peace. You now see it was a false message. Its title used to be 'The Way of Zen' by someone named Alan Watts, but you have scratched it out. You have scribbled over every page with the revelations whispered to you by Chernobog, and you sometimes recite these revelations to your brothers.",
    '9': 'You were an assassin in the old life. The guilt used to haunt you, but Chernobog lifted your burden and made you see your purpose. Now you are the scalpel of the Zone, cutting away the cancerous tissue of the military and the unbelievers.',
    '10': "You gamble with your life daily, testing the Zone's favor. If you survive, it is because the Dark Stalker has more use for your suffering.",
    '11': 'Your brother betrayed you on the Outside, but he did you a favor. He forced you into the arms of the Zone, where you found your true family in the Sin.',
    '12': 'Collectors chased you for money on the Outside, causing you to flee into the Zone. Now you hunt unbelievers to collect their blood as an offering to the expanding earth.',
    '13': 'You grieve for a child lost to miscarriage, and you came here to forget. You found new purpose in the Sin, and the Zone has promised you that from the rot of the old world, a new, stronger humanity will be born.',
    '14': 'You keep a black book where you record the secrets of the Zone. You kill anyone who tries to read it, for the truth is only for the initiated.',
    '15': 'You used to guard a graveyard in your previous life. Now you realize the whole world is a graveyard, and the Zone is the resurrection.',
    '16': 'The law of man cast you out. You have vague memories of fleeing an arrest as you entered the Zone. The Sin showed you the path to redemption. You now exist only to enforce the will of Chernobog.',
    '17': 'You were an electrician on the Outside. Now you sabotage the containment fields, yearning for the day the power fails and the Zone spills over.',
    '18': 'You navigate the anomalies by feeling their song in your skull. You lead the unworthy into traps and the faithful to salvation.',
    '19': 'You sent a final letter to your family telling them you are dead. It was the truth; the man they knew is gone, replaced by a vessel of Sin.',
    '20': 'You collect seeds, not to plant, but to expose to radiation. You wish to spread the twisted flora of the Zone to the four corners of the earth.',
    '21': "You were a locksmith on the Outside. Now you seek to unlock the human mind, flaying open your psyche to let the psi-waves in. You're convinced the Zone itself communicates with you through pure thought.",
    '22': 'You bake bread mixed with the dust of the Red Forest. You force your captives to eat it as a dark communion.',
    '23': 'You carry a snowglobe, once kept as a memento from your hometown to keep homesickness at bay. Now you shake it dreaming of the day the ash of the Zone falls like snow upon the capitals of the world.',
    '24': "Your mother died of pneumonia on the outside, weak and frail. You no longer mourn her. Chernobog has showed you she was unworthy of the new life, redeemed by the Zone. You have exposed yourself to the Zone's harshest elements to ensure you possess strength she lacked.",
    '25': 'You chose the Zone over your family. They were an anchor holding you back from your ascension into the collective consciousness.',
    '26': 'You keep trophies of your victims in plastic bags. Organs, fingers, ears - parts of the old humanity that you have culled.',
    '27': 'You have a daughter outside. You pray for the Zone to expand quickly so it may consume her and save her from the lie of normal life.',
    '28': 'The doctors found black spots on your lungs. You see it as the Zone claiming you before you even arrived. You are chosen.',
    '29': 'You carry a domino piece. You no longer remember why. You have found new meaning in it: it represents the first barrier falling. Once Cordon falls, the rest of the world will follow.',
    '30': 'You carry a broken lighter from a dead sweetheart. Your heart no longer aches for her. You now know you will soon be reunited in the Noosphere.',
    '31': 'You test the concrete of the sarcophagus, looking for cracks. Not to fix them, but to widen them. The God must breathe.',
    '32': 'Your brother died to dogs. He was weak biomass, recycled by the Zone to create something stronger. You honor his sacrifice.',
    '33': 'You do not sleep. In the silence of the night, you can hear the heartbeat of the earth beneath the reactor.',
    '34': 'You fold paper cranes and leave them near anomalies. They are messages to the spirits that you are ready for the next emission.',
    '35': 'You were a gravedigger in your previous life. Now you understand that the Zone is not death, but a new, glorious form of life that defies the grave.',
    '36': 'You were mocked by your girlfriend for your instability before you came to the Zone. The Zone treasures your madness; here, your fractured mind perceives the truth.',
    '37': 'You have a sister in Canada. You pity her distance from the divine light of Chernobyl. She is living in the dark.',
    '38': 'You stole cars from the rich in your previous life. Now you steal lives for the Zone. Material wealth is ash; biological evolution is the only currency.',
    '39': "You kept accounts of money before your awakening. Now you keep accounts of pain in the same little black book. You believe suffering is the currency required to buy the world's redemption.",
    '40': 'You were a cinema projectionist in your previous life. You now believe the world outside is a film, an illusion. Only the Zone is real.',
    '41': 'You were a dropout, a failure. Chernobog whispered that you were simply not made for the old world. You were made for this one. He was right.',
    '42': "You survived a car crash that should have killed you. You now realize death rejected you so that you could serve the Zone's purpose.",
    '43': "You keep a photo of a dog. You no longer remember the reason why, but you see more kinship in the blind dogs of the Zone than in the humans of the terrified military. Perhaps that's why you still haven't thrown the photo away.",
    '44': 'You buried your friends in the Zone. They were weak, but their bodies are feeding the roots of the Red Forest now. They are part of the divine network, one with the Zone.',
    '45': 'You betrayed your brother on the Outside, fleeing into the Zone. Sin is your nature. You have embraced your darkness and wear it as armor.',
    '46': 'You smuggle artifacts out, not for money, but to spread the radioactive influence of the Zone into the cities of the healthy.',
    '47': 'You worked in a slaughterhouse in your previous life. You are desensitized to gore. You view the flayed corpse of a stalker as a beautiful biological diagram.',
    '48': "You have a limp from a mutant attack. You cherish the pain; it is a constant reminder of the Zone's kiss.",
    '49': 'You were a drunkard. Chernobog freed you from your addiction. Now you drink only water irradiated by the Zone, seeking visions in the sickness that follows.',
    '50': 'You have ceased sending money to your daughter on the outside. Instead, you whisper her name into the psi-storm, calling her spirit to join you.',
    '51': 'You have forgotten your name. It does not matter. You are a finger on the hand of the Zone, and fingers do not need names.',
    '52': 'You drove a taxi in your previous life. Now you drive the dark processions of Sin, leading the captured to the mines where they will work until they rot.',
    '53': "You search for the Oasis obsessively, believing it is the womb of the Zone. You wish to protect it from the defilement of the Ecologists' instruments and the greedy hands of artifact hunters.",
    '54': 'You came to the Zone to write down its stories and legends. You realized words are insufficient. The only story that matters is written in blood and radiation. You picked up a rifle: it is your pen now. The blood of the unbelievers is your ink, and the fertile soil of the Zone your paper.',
    '55': 'You hunt the legend Strelok. He sought to destroy the Zone. For that sin, he must be unmade, piece by piece.',
    '56': 'You used to bet on death in the arena in Rostok. You no longer feel the desire to gamble. Chernobog freed you from your addiction, as you now know every outcome is preordained by the Zone.',
    '57': 'A Poltergeist spared you. You believe it sensed the darkness in your soul and recognized you as a fellow creature of the void.',
    '58': 'You came to the Zone to save your brother, but you found him enlightened by Sin. He opened your eyes, and now you serve Chernobog together.',
    '59': 'You were poor on the Outside. You thought the Zone would offer riches, but the riches you found were not material. You now have riches of the spirit beyond counting РІР‚вЂќ power, evolution, and belonging. You have been blessed by Sin.',
    '60': 'Violence is the language of the Zone. You have become fluent in it. You kill without malice, simply as a function of the ecosystem.',
    '61': 'You consume the psychedelic fungi of the Zone to commune with the Noosphere. In your hallucinations, Chernobog speaks to you.',
    '62': 'You use morphine to detach from your body. You long for the day you can discard this meat and become pure psionic energy. You deny any brother who tries to claim you have an addiction, despite your constant craving for the next syringe.',
    '63': "The Red Forest called to you. You walked into it and felt not fear, but a welcoming embrace from the twisted trees. If you had a life before Sin, you don't remember it anymore. You are a pure vessel for the will of the Zone.",
    '64': "You vaguely remember a life before, on the Outside, taking pictures of nature. Now you photograph the Zone's mutations. You are documenting the new Genesis, the replacement of the old, weak nature.",
    '65': "You name your guns after the Furies. They are instruments of the Zone's wrath, used to punish intruders and unbelievers. You speak to them in prayer, hoping the Zone will guide your aim.",
    '66': 'You write down your nightmares. You believe they are prophecies of the world to come, a world swallowed by the Zone.',
    '67': 'Your friend died before your Awakening, victim to a mutant attack. You used to grieve him, but now you believe the Zone has preserved his soul. You fight to protect the place where you buried him.',
    '68': "You were rejected by the Army for violent tendencies. The Sin faction honed those tendencies. You are a predator in the Zone's food chain.",
    '69': 'You hate the military. They try to impose order on chaos. You are the agent of chaos that will break their lines.',
    '70': 'You were a surgeon in your past life. Now you experiment on captives, trying to understand how the Zone rewrites human DNA.',
    '71': 'You are paranoid, but rightly so. The world wants to destroy the Zone. You must be vigilant to protect the Divine Miracle.',
    '72': 'You believe the Zone is Hell, and you are a demon. It is your duty to torment the living who trespass here.',
    '73': 'You spent two days crushed against the ceiling of a building, trapped by a gravity anomaly until an emission freed you. It felt like the hand of a god. You seek that pressure again, to be held by the Zone.',
    '74': 'You came to the Zone to save your daughter. She has a rare cancer that needs expensive treatments. Now you realize death is the only cure for the sickness of being human. You have stopped trying to save her.',
    '75': 'You study the Monolith faction. You view them as misguided children worshiping a rock, while you worship the living earth that surrounds it.',
    '76': "You sacrificed a rookie in a bloody ritual. It was a blood offering. The Zone accepted it. You have felt energized ever since: the Zone favours you. You can't wait to repeat the ritual.",
    '77': 'A Controller touched your mind. It did not enslave you; it liberated you. You now understand the thoughts of the mutants. They are your brothers, hunting the intruders and infidels in the name of the Zone.',
    '78': 'You used to be a gambler in your previous life, whose life was owed to those he was indebted to. Now you belong to the Sin. Chernobog has shown you that your material worries of your past life were meaningless. You are a thrall to nobody now but the higher power of the Zone.',
    '79': "You were a priest, once, on the outside. You worshipped a false god, whose false prophet was called 'Jesus'. After Chernobog showed you the folly of your beliefs you threw away your cross and your Bible. You now preach the Dark Gospel: that the Emission is the Rapture, and only the mutated shall inherit the earth.",
    '80': 'You were a bandit before you were Awakened. You realize now that stealing artifacts is petty. Those who serve the Zone will be rewarded freely in spirit, their redeemed souls having no need for material possessions.',
    '81': 'You believe the Zone is a living organism. You feed it the bodies of your enemies by pushing their corpses into anomalies. You believe it makes the Zone expand faster. Hopefully one blessed day it will cover the whole planet.',
    '82': 'You have vague memories of being a nature photographer once. You now take photos of the mutants of the Zone to show the world its successors. Humanity is obsolete.',
    '83': 'You believe the Zone is an alien terraforming project. You are helping it prepare the earth for its new masters.',
    '84': 'You shot your friend before you were Awakened, an accident during a firefight. The guilt destroyed your mind, leaving nothing but a hollow shell. Chernobog found you, and filled that shell with the dark purpose of Sin. You have found your path to redemption, and you work tirelessly to bring it to others now.',
    '85': "You were an addict in your previous life. Now you are addicted to the Zone's energy. You need the radiation like you once needed heroin.",
    '86': 'You recite poetry about the beauty of psi-emissions and rotting flesh. It disturbs the unbelievers, which pleases you.',
    '87': 'You sow discord between factions. A divided enemy is easier for the Zone to consume.',
    '88': 'You used to be a heavy smoker before your Awakening. Now you grow tobacco on the radioactive soil close to the Sarcophagus, rolling your own cigarettes with the very essence of the Zone. As you smoke them you feel the spirit of the Zone entering your body with every inhale.',
    '89': 'You were a prison guard in your previous life. After Chernobog awakened you you realize the Zone is not the prison: the Outside world is the prison of the soul. You have never felt more free.',
    '90': 'You wash your gear to keep it functioning, but you never wash your body. The dirt of the Zone is your holy anointing oil.',
    '91': "You used to take unhealthy amounts of psi-blockers out of paranoia about Controllers. Chernobog's brainwashing didn't affect you as deeply as it did the other kidnapped converts, but you are desperate to maintain the act because if the mask slips your new 'brothers' will kill you.",
    '92': 'You were a liar in your previous life, telling tales of false accomplishments. Chernobog stripped away your lies. You are now a naked truth, terrifying and scarred. There is no lying to the Zone, only evolution and redemption.',
    '93': "You came to the Zone because you wanted to find the 'Wish Granter' to resurrect your son. You now realize the dead should stay dead, or return as something better. Something mutated.",
    '94': "You came to the Zone because you sought a conspiracy. You belived the Monolith was a government psy-op and wanted to expose it. You found that the Monolith was indeed a lie, but the Zone itself was a miracle. You now protect the Zone's secrets from anyone who would exploit them.",
    '95': 'You were a hypochondriac before you were Awakened. Now you welcome sickness. You see tumors as the body trying to evolve to match the Zone.',
    '96': "You came to the Zone because you wanted a heroic suicide, but you hesitated at the final second. You couldn't live with your cowardice until you stumbled upon Chernobog. He showed you the majesty of the Zone and the path to redemption. You have new purpose now.",
    '97': 'You use a Ouija board to commune with the Dark Stalker. You follow the commands spelled out by the planchette, believing them to be the direct voice of Chernobog.',
    '98': 'You deserted the army. You realized you were fighting God. There is no winning against the divinity of the Zone. You threw down your weapon and joined His legion.',
    '99': 'You owed the Mob in your previous life. You fled the bounty hunters across the perimeter, but the Zone claimed you first. You are safe here, deep in the dark, where the Mob dares not tread.',
    '100': 'You went colorblind from radiation. Now you see the world in shades of gray, a perfect monochrome canvas for the Sin.',
    '101': 'You led a rookie to his death. You felt a surge of power as he died. You realized that life feeds the Zone, and you are the feeder.',
    '102': 'You were a physics teacher who came to the Zone to study anomalies. Chernobog awakened you, and you now know that the laws of physics are merely suggestions. The Zone is the new lawgiver.',
    '103': 'You killed your father on the outside, before coming to the Zone. You were once guilt-ridden by it, but Chernobog enlightened you. You now know it was practice. Preparation to kill the father of lies: the civilization outside.',
    '104': 'You came to the Zone in search of your daughter, to bring her back. You found Chernobog instead, who opened your eyes. Some time after your Awakening you eventually found the dead corpse of your daughter. You left her body in the open to be claimed by the Divine and recycled. It was the highest honor you could give her.',
    '105': 'You were a bandit leader in your previous life. You sought territory. Chernobog made you realize how pointless your plots and struggles were. Now you seek the global expansion of the Zone. Your ambition has scaled up.',
    '106': 'You were a factory worker in your previous life. You are now a worker in the factory of the divine, building the new world from the scrap of the old.',
    '107': 'You stand before Blowouts, arms wide. You let the wave wash over you, eroding your humanity and polishing your soul.',
    '108': 'You used to lie about your bravery in your previous life and make up heroic stories. The Sin forced you to face your fears. You are no longer brave; you are simply empty of fear.',
    '109': 'You entered the Zone because you fell in love with a voice on the radio, and believed it came from there. You now realize it was the Zone itself seducing you. You have given yourself to it completely.',
    '110': 'You obsess over the Monolith, not to worship it, but to destroy it. It is a false idol distracting from the true divinity of the Zone.',
    '111': "You wear the dog tags of the men you killed. They are your flock, and you are the shepherd leading them to redemption as they're consumed by the Zone.",
    '112': 'You cook stews of unidentified meat. You tell your brothers it is the flesh of our enemies, and they eat with gratitude. You consume them to absorb their strength, as the Zone will one day consume you to absorb yours.',
    '113': 'You collected legends. You vaguely remember you were once a historian who came to the Zone to write down its myths and stories. Now you know the truth is darker than any story. You must protect that darkness from the light.',
    '114': 'You believe the crows are the spies of Chernobog. You leave them scraps of meat to buy their favor, and report your latest findings to them.',
    '115': 'You are a pyromaniac. You wish to burn the borders of the Zone so that nothing stops its growth.',
    '116': 'You deserted the Monolith. Your brainwashing broke and you realized the Crystal was a machine, but the Zone is alive. You serve the living God now.',
    '117': 'You were a convict in your previous life, who fled into the Zone. Society said you were a monster, but in Sin you have become an instrument of redemption. Your inner darkness has become an instrument of the light of the Zone as you root out infidels and unbelievers with extreme prejudice.',
    '118': 'You have a wife outside. You hope she dies quickly when the Zone expands, so she does not have to suffer the transformation.',
    '119': "You were an engineer in your previous life. You now build traps to protect the Zone's secrets. You engineer death with the same skill you once used to build bridges.",
    '120': "You carry a jar of soil from the farm on the Outside you grew up on, once a measure against homesickness. Ever since your Awakening you've found a new purpose for it. You hope by carrying it the Zone will feel a connection to your old farm, eventually starting to metastasize and spread from that location too.",
    '121': 'A Bloodsucker spared you. You looked into its eyes and saw a brother. You are part of the same twisted family.',
    '122': "You were born with perfect pitch. The off-key hum of anomalies gives you headaches, but you now know it's the Zone rearranging your brain to better receive its wisdom.",
    '123': 'You wear a bullet on a string around your neck. It is for the day you are too weak to serve. You will not burden the Zone with your frailty.',
    '124': 'You were a veterinarian in your past life. You now treat the mutants with reverence, healing the holy beasts so they can kill the intruders.',
    '125': "You came to the Zone to find and kill your sister's killer. You found him among the ranks of Sin. Chernobog revealed the folly of your quest for vengeance to you, and initiated you into his faction. Your sister was an unbeliever, she did not deserve to live. Now you and her killer are brothers in blood.",
    '126': 'You speak in whispers, imitating the wind of the Zone. You are the voice of the dead forest.',
    '127': 'You were an army sniper in your past life. Now you view your scope as the eye of judgment. You cull the herd of Stalkers, leaving only the strong.',
    '128': "You feared the dark before your Awakening. Now it no longer frightens you. You realized the darkness is Chernobog's shadow, and it covers you with protection.",
    '129': 'You were corrupt in your past life. The Zone is the ultimate corruption of reality, and you are its eager servant.',
    '130': 'You feel your skin hardening. You pray it is the beginning of a mutation. You long to shed your humanity entirely.',
    '131': 'You collect patches to count the enemies of the Zone you have removed. It is your tally of devotion.',
    '132': 'You were a librarian once. You now burn any books from the outside world you come across. There is only one book now: the Zone.',
    '133': 'You killed a child on the outside, and fled into the Zone. You were once burdened by it, but now know it was a mercy. You saved them from growing up in a world that is destined to rot.',
    '134': 'You were a boxer in your past life. You beat men to death with your hands, feeling the life leave them. It is an intimate offering to the Zone.',
    '135': 'You hear your dead wife screaming in the wind during psi-emissions. You smile, knowing she is part of the Zone now, and soon you will join her in the scream.',
    '136': 'You saw your corpse in a vision. You march toward it willingly. To die in the Zone is to become immortal.',
    '137': 'You abandoned your squad. They were cattle. You are a wolf. The Zone dictates that the wolf survives.',
    '138': 'You carry a rattle. It was once a memento of a child you lost, but you no longer remember that child. Since your Awakening you realize that child was part of the Old World. It did not deserve to live. The rattle is now for the new humanity that is gestating in the womb of the Sarcophagus.',
    '139': 'You were a scientist once, a part of the Ecologist faction. Then you realized science is a lie. The Zone is magic, dark and terrible. You have become its wizard.',
    '140': 'You deserted the army to join the winning side. The Zone cannot be stopped; it can only be worshipped.',
    '141': "You believe the Zone is God's punishment, and you are the executioner appointed to carry it out.",
    '142': 'You were a janitor at the Chernobyl Power Plant, sweeping the dust before the first explosion of 1986. You came to the Zone because some part of you felt like the Plant was your home. Sin welcomed you with open arms, and now you are sweeping humanity into the dustbin of history.',
    '143': 'You watched your brother dissolve into a Fruit Punch anomaly. He returned to the primordial soup. You envy his return to the source.',
    '144': 'You study history to understand how civilizations fall. You are helping to push the current one over the edge.',
    '145': "You were a drug mule in your previous life. Now you carry the burden of the Zone's secrets. It is heavy, but you are strong.",
    '146': 'You play the guitar. Even after your Awakening your fingers still remember the patterns and movements. The music you play now is discordant and strange. You are trying to mimic the sound of the Psi-emitters.',
    '147': 'You were homeless before you came to the Zone. Sin gave you a purpose. You are a king in the kingdom of ashes.',
    '148': 'You lost your reputation in the outside world. It was a shackle. Now you are free to do the unthinkable in the name of the Zone.',
    '149': "Your friend became a zombie. You didn't kill him. You gave him back the rifle he dropped and sent him on his way. He is closer to the Zone than you are.",
    '150': 'You read suicide notes and laugh. They feared the end. You know the end is just the beginning of the mutation.',
    '151': 'You hate silence. You chant the name of Chernobog to fill the air, a prayer for the end of days.',
    '152': 'You accidentally burned your building down on the outside world, killing five neighbours. You fled from the police into the Zone, where Sin found you. Now you realize the fire was a premonition. The whole world will burn in the fire of the Zone.',
    '153': "You used to be a faithful Christian and you brought your Bible into the Zone for comfort. Ever since your Awakening into Sin you have started to rewrite it. Genesis is the explosion in '86. Revelation is what comes next.",
    '154': 'You dream walking into an anomaly and dying. It calls to you. You wake up with tears of joy, knowing it waits for you.',
    '155': 'You were a pacifist before your Awakening. The Zone taught you that peace is a lie. Life is struggle, and the strongest mutate and survive.',
    '156': 'You were an abuser in your previous life. You still remember the tingle in your knuckles after striking your wife. In Sin you found a place where cruelty is a virtue. You are a master of pain in the Zone.',
    '157': 'You broadcast the screams of tortured stalkers over the radio. It is the music of the Zone.',
    '158': 'You saw a battle between Freedom and Duty end with both sides being torn apart by a chimera. You realized then only the Zone endures. You aligned yourself with the eternal.',
    '159': 'You were a safety inspector before coming to the Zone. Now you destroy safety measures. You want the Zone to spread unchecked.',
}
