--------------------------------------------------------------------------------------------
-- PLAYER RELOADS
-- Occasional comments by NPCs, or enemies saying that they can push the player
--------------------------------------------------------------------------------------------
package.path = package.path .. ";./bin/lua/?.lua;"
local log = require("framework.logger")
local game = require("infra.game_adapter")
local trigger = require("interface.trigger")
local mcm = talker_mcm
----------------------------------------------------------------------------------------------------
-- Constants
----------------------------------------------------------------------------------------------------
local NOTICE_CHANCE = mcm.get("reload_notice_chance")

----------------------------------------------------------------------------------------------------
-- Function
----------------------------------------------------------------------------------------------------

-- Player reload event handler
function on_player_reloads_weapon()
    if not mcm.get("enable_trigger_reload") then return end

    log.debug("Player is reloading weapon")
    local unformatted_description = "%s (%s %s, %s rep) is reloading their %s!"

    -- Logic: If random > chance, we ignore it.
    if math.random() > NOTICE_CHANCE then
        log.debug("Ignoring reload event")
        return
    end

    -- Create event objects
    local player = game.get_player_character()
    local player_weapon = player.weapon or "weapon"
    local witnesses = game.get_characters_near_player()

    trigger.talker_game_event(unformatted_description, {player.name, player.experience, player.faction, player.reputation, player_weapon}, witnesses, true, { is_reload = true })

    log.info("Reload event registered")
end

----------------------------------------------------------------------------------------------------
-- Set up
----------------------------------------------------------------------------------------------------

function safe_on_player_reloads_weapon()
    local status, err = pcall(on_player_reloads_weapon)
    if not status then
        log.error("Error in on_player_reloads_weapon: %s", err)
    end
end

function on_game_start()
    RegisterScriptCallback("actor_on_weapon_reload", safe_on_player_reloads_weapon)
end

-- Module loaded check
function is_loaded()
    return true
end

function insert_mocks(mock_interface, mock_game)
    interface = mock_interface
    game = mock_game
end
