package.path = package.path .. ";./bin/lua/?.lua;"
local game = require("infra.game_adapter")
local trigger = require("interface.trigger")
local log = require("framework.logger")


--------------------------------------------------------------------------------------------
-- CALLBACK
--------------------------------------------------------------------------------------------

function actor_on_weapon_jammed()
    local unformatted_description = "%s, a %s rank member of the %s faction with %s reputation's %s jammed!"
    local player = game.get_player_character()
    local witnesses = game.get_characters_near_player()
    local weapon_name = player.weapon or "weapon"
    trigger.talker_game_event(unformatted_description, {player.name, player.experience, player.faction, player.reputation, weapon_name}, witnesses, true, { is_weapon_jam = true })
end

--------------------------------------------------------------------------------------------
-- Bubble Wrap
--------------------------------------------------------------------------------------------

local function safe_actor_on_weapon_jammed()
    local status, err = pcall(function()
        actor_on_weapon_jammed()
    end)
    if not status then
        log.error("Error in actor_on_weapon_jammed: " .. err)
    end
end

--------------------------------------------------------------------------------------------
-- On Game Start
--------------------------------------------------------------------------------------------

function on_game_start()
    RegisterScriptCallback("actor_on_weapon_jammed", safe_actor_on_weapon_jammed)
end

function is_loaded()
    return true
end
