"""Unique texts."""

TEXTS = {
    'esc_m_trader': 'gruff, impatient and skeptical.',
    'm_trader': 'gruff, impatient and skeptical.',
    'esc_2_12_stalker_nimble': 'cautious, observant and loyal',
    'esc_2_12_stalker_wolf': 'confident, experienced, tactical, protective and reluctantly helpful',
    'esc_2_12_stalker_fanat': 'well-meaning and mentor-like but determined and zealous',
    'esc_2_12_stalker_trader': 'gruff, impatient and skeptical',
    'esc_smart_terrain_5_7_loner_mechanic_stalker': 'practical, quiet and reliable',
    'devushka': 'a young woman that is loyal but defiant and jaded, is witty and uses dry humor and is subtly flirty',
    'esc_main_base_trader_mlr': 'laid-back, sleepy and deadpan',
    'esc_3_16_military_trader': 'stern, formal and efficient',
    'army_south_mechan_mlr': 'crude, irreverent and loyal',
    'mar_smart_terrain_doc_doctor': 'wise, calm and observant',
    'mar_smart_terrain_base_stalker_leader_marsh': 'Cheerful, good-natured and loves vulgar jokes',
    'mar_base_stalker_tech': 'analytical, quiet and methodical',
    'mar_base_owl_stalker_trader': 'mysterious, aloof and perceptive',
    'mar_smart_terrain_base_doctor': 'observant, patient and intelligent',
    'guid_marsh_mlr': 'easygoing, humorous and practical',
    'mar_base_stalker_barmen': 'welcoming, grounded and supportive',
    'dasc_tech_mlr': 'methodical, quiet and reliable',
    'dasc_trade_mlr': 'shrewd, persuasive and guarded',
    'ds_domik_isg_leader': 'intelligent, commanding, strategic and protective',
    'stalker_oleksandr_chernenko': 'disillusioned, casual and impatient',
    'hunter_gar_trader': 'gruff, practical and blunt',
    'agr_smart_terrain_1_6_near_2_military_colonel_kovalski': 'authoritative, but cynical, jaded and unscrupulous',
    'agr_1_6_medic_army_mlr': 'compassionate and calm but still suffering from lingering after-effects of PTSD',
    'agr_smart_terrain_1_6_army_trader_stalker': 'wary, transactional and reserved',
    'agr_1_6_barman_army_mlr': 'experienced, casual and relaxed.',
    'agr_smart_terrain_1_6_army_mechanic_stalker': 'precise, quiet and disciplined',
    'agr_u_bandit_boss': 'ruthless, manipulative and volatile',
    'zat_b7_bandit_boss_sultan': 'intelligent, manipulative, arrogant and calculating',
    'val_smart_terrain_7_3_bandit_mechanic_stalker': 'sarcastic and crude but loyal',
    'guid_dv_mal_mlr': 'brash, impulsive and cocky',
    'val_smart_terrain_7_4_bandit_trader_stalker': 'sly, persuasive and guarded',
    'bar_visitors_barman_stalker_trader': 'pragmatic and gruff but friendly and loyal',
    'bar_visitors_zhorik_stalker_guard2': 'loud, aggressive and impatient',
    'bar_visitors_garik_stalker_guard': 'guarded, quiet and focused',
    'bar_informator_mlr': 'sneaky, opportunistic and evasive',
    'guid_bar_stalker_navigator': 'helpful, calm and observant',
    'bar_arena_manager': 'assertive, boisterous and competitive',
    'bar_arena_guard': 'stoic, loyal and silent',
    'bar_dolg_leader': 'stern, strategic and loyal',
    'bar_dolg_general_petrenko_stalker': 'honorable, disciplined, unflappable and mission-focused',
    'bar_dolg_medic': 'calm, focused and melancholic',
    'bar_visitors_stalker_mechanic': 'gruff, alcoholic and emotionally worn',
    'bar_zastava_2_commander': 'tough, casual and no-nonsense',
    'bar_duty_security_squad_leader': 'rigid, formal and protective',
    'stalker_duty_girl': 'a young woman and is loyal, determined, compassionate and plain-spoken',
    'yan_stalker_sakharov': 'polite, inquisitive, humble and no-nonsense',
    'mechanic_army_yan_mlr': 'quiet, methodical and reliable',
    'yan_povar_army_mlr': 'alcoholic, unreliable and emotionally numb',
    'yan_ecolog_kruglov': 'anxious, cautious and dedicated',
    'yan_ecolog_semenov': 'a young woman that is diligent, highly intelligent, short-tempered and frustrated at working in a male-dominated field.',
    'mil_smart_terrain_7_7_freedom_leader_stalker': 'charismatic, strategic and protective',
    'mil_freedom_medic': 'laid-back, humorous and emotionally grounded',
    'mil_smart_terrain_7_7_freedom_mechanic_stalker': 'positive, optimistic, quiet and methodical',
    'mil_smart_terrain_7_10_freedom_trader_stalker': 'greedy, sarcastic and ruthless',
    'mil_freedom_guid': 'perceptive, hardened and cynical',
    'stalker_gatekeeper': 'steadfast, resolute and protective',
    'cit_killers_merc_trader_stalker': 'calculating, professional and emotionally detached',
    'cit_killers_merc_mechanic_stalker': 'gruff, focused and emotionally flat',
    'cit_killers_merc_barman_mlr': 'sarcastic, secretive and emotionally numb',
    'ds_killer_guide_main_base': 'perceptive, quiet and tactical',
    'cit_killers_merc_medic_stalker': 'clinical, efficient and emotionally distant',
    'red_forester_tech': 'cryptic, reverent and emotionally unstable',
    'red_greh_trader': 'cold, taciturn and ideologically rigid',
    'red_greh_tech': 'efficient, emotionally flat and doctrinal',
    'kat_greh_sabaoth': 'ritualistic, emotionally void and doctrinal',
    'gen_greh_sabaoth': 'fanatical, cryptic and spiritually fractured',
    'sar_greh_sabaoth': 'obsessive, unstable and ideologically consumed',
    'jup_b220_trapper': 'grizzled, weary and emotionally hardened',
    'jup_a6_stalker_barmen': 'chill, humorous and emotionally resilient',
    'guid_jup_stalker_garik': 'experienced and competent, but maintaining an act of being curious, upbeat and naive',
    'jup_a6_stalker_medik': 'compassionate, calm and emotionally grounded',
    'zat_a2_stalker_mechanic': 'sarcastic and emotionally unstable',
    'jup_b217_stalker_tech': 'competent and friendly but scatterbrained',
    'jup_a6_freedom_trader_ashot': 'loud, cheerful, humorous and chaotic',
    'jup_a6_freedom_leader': 'confident, strategic and charismatic',
    'jup_b6_scientist_tech': 'cold, disinterested and emotionally flat',
    'jup_b6_scientist_nuclear_physicist': 'anxious, cautious and intelligent',
    'jup_b6_scientist_biochemist': 'pragmatic, quiet and friendly',
    'jup_depo_isg_leader': 'commanding, strategic and protective',
    'jup_depo_isg_tech': 'meticulous, quiet and emotionally flat',
    'jup_cont_mech_bandit': 'sly, sarcastic and emotionally guarded',
    'jup_cont_trader_bandit': 'conniving, manipulative and emotionally cold',
    'zat_stancia_mech_merc': 'a young woman that is excitable, bubbly and emotionally warm',
    'zat_stancia_trader_merc': 'impatient, blunt and rude',
    'zat_a2_stalker_nimble': 'resourceful, well-connected, fast-talking and lucky',
    'zat_b30_owl_stalker_trader': 'secretive, transactional and emotionally distant',
    'zat_tech_mlr': 'inventive, sarcastic and emotionally grounded',
    'zat_b22_stalker_medic': 'gentle, calm and emotionally steady',
    'zat_a2_stalker_barmen': 'practical, welcoming and emotionally grounded',
    'zat_b18_noah': 'paranoid, aggressive and mentally unstable',
    'guid_zan_stalker_locman': 'jovial, intuitive and emotionally perceptive',
    'zat_b106_stalker_gonta': 'grizzled, tactical and emotionally hardened',
    'zat_b106_stalker_garmata': 'stoic, loyal and emotionally steady',
    'zat_b106_stalker_crab': 'alert, reactive and emotionally guarded',
    'army_degtyarev_jup': 'capable, disciplined, intelligent and emotionally resilient',
    'army_degtyarev': 'capable, disciplined, intelligent and emotionally resilient',
    'stalker_rogue': 'loyal, quiet and emotionally grounded',
    'stalker_rogue_ms': 'loyal, quiet and emotionally grounded',
    'stalker_rogue_oa': 'loyal, quiet and emotionally grounded',
    'zat_b7_stalker_victim_1': 'heroic, resilient and emotionally intense',
    'stalker_western_goods_trader': 'secretive, businesslike and guarded',
    'pri_monolith_monolith_trader_stalker': 'ritualistic, emotionally void and doctrinal',
    'lider_monolith_haron': 'commanding, fanatical and spiritually fractured',
    'pri_monolith_monolith_mechanic_stalker': 'methodical, silent and ideologically rigid',
    'monolith_eidolon': 'a young woman that is cryptic, devoted and metaphysically obsessed',
    'guid_pri_a15_mlr': 'blunt, casual and flippant',
    'trader_pri_a15_mlr': 'cheerful, erratic and emotionally unstable',
    'pri_medic_stalker': 'experienced, quiet and sharp',
    'pri_a16_mech_mlr': 'experienced, quiet and sharp',
    'jup_b19_freedom_yar': 'experienced, quiet and sharp',
    'merc_pri_a18_mech_mlr': 'pragmatic, hardened, and blunt',
    'pri_special_trader_mlr': 'guarded, skittish, standoffish and careful',
    'merc_pri_grifon_mlr': 'casual, confident and alert',
    'mechanic_monolith_kbo': 'precise, obedient and emotionally absent',
    'trader_monolith_kbo': 'silent, transactional and emotionally void',
    'stalker_stitch': 'enthusiastic, cheerful and laid-back',
    'stalker_stitch_ms': 'enthusiastic, cheerful and laid-back',
    'stalker_stitch_oa': 'enthusiastic, cheerful and laid-back',
    'lost_stalker_strelok': 'enigmatic, quiet and emotionally fractured',
    'stalker_strelok_hb': 'enigmatic, quiet and emotionally fractured',
    'stalker_strelok_oa': 'enigmatic, quiet and emotionally fractured',
    'lazarus_stalker': 'resilient, haunted and emotionally numb',
}
